### ISSUE TITLE
首页公告内容支持更多格式

### ISSUE THREAD

**Issue by Rennen0929** [wan92hen/theme-terminal#10]
谢谢开发者移植主题
在使用过程中发现首页公告内容不支持换行
解决方法是修改 `/templates/index.html`  文件

![image](https://github.com/wan92hen/theme-terminal/assets/89285206/adfb221d-d1d9-46b9-affc-6c6492271057)

测试效果如图

![image](https://github.com/wan92hen/theme-terminal/assets/89285206/fe0cf435-9894-48cc-a7d4-450d7d8f5c4b)
![image](https://github.com/wan92hen/theme-terminal/assets/89285206/f6db090f-fef6-44ec-8b0e-52904908dafa)

参考资料：
[thymeleaf中th:text和th:utext的区别](https://blog.csdn.net/rongxiang111/article/details/79678765)
因为我不太熟悉前端，所以暂时也想不到更好的解决方案，不知道这个方案是否可行 🙈

**Comment by wan92hen** [comment]
感谢提出的问题及修改。
