### ISSUE TITLE
文章评论貌似无法显示

### ISSUE THREAD

**Issue by Rennen0929** [wan92hen/theme-terminal#12]
如题，[我的博客](https://rennen.dev/archives/ce-shi-wen-zhang-fa-bu)中文章评论好像无法显示，求指导

[官方文档里要求添加标签适配评论组件](https://www.halo.run/store/apps/app-YXyaD#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D)，但是我好像没在代码里找到这个标签在哪 🙈 

 #8 看了这个 Issue，文章评论是正常显示的，我这里不知道为什么不行

环境是 halo 最新版：2.9.2

主题使用的是最新发行版 0.0.6，已安装 Halo 官方评论插件并启用评论功能

**Comment by wan92hen** [comment]
不好意思之前确实是漏了，已在 756260d9991bd3baf373f50405ad9575f410f1f6 中修改

**Comment by wan92hen** [comment]
发布了 [v0.0.7](https://github.com/wan92hen/theme-terminal/releases/tag/v0.0.7) 解决这个问题，[v0.0.7](https://github.com/wan92hen/theme-terminal/releases/tag/v0.0.7) 里同时支持了瞬间插件。

**Comment by Rennen0929** [comment]
非常感谢！辛苦了
