### ISSUE TITLE
请问这个主题可以进行代码高亮吗？

### ISSUE THREAD

**Issue by FunnyWii** [wan92hen/theme-terminal#17]
首先感谢作者做出来这么好看的主题！

我在使用halo2.17自带的编辑器输入代码时，在预览界面发现并没有任何的代码高亮，

![image](https://github.com/user-attachments/assets/b5062b48-b452-4384-b890-671690b7387f)
![image](https://github.com/user-attachments/assets/8f0a2cac-9a4f-4b65-b81c-650ecef97dd1)

请问这是我操作方式不对还是这个主题不支持代码高亮？

**Comment by wan92hen** [comment]
你好，可以额外安装下 highlight.js 这个插件：https://www.halo.run/store/apps/app-sqpgf

**Comment by FunnyWii** [comment]
谢谢！
🤣确实有了一定代码高亮的效果，不过希望您早日内置这个功能。您提到的这个插件，用在您开发的主题下面，风格不太搭


BugKing ***@***.***> 于2024年7月23日周二 10:15写道：

**Comment by wan92hen** [comment]
在这个插件设置中可以选择主题的。

**Comment by FunnyWii** [comment]
感谢！已经调整好啦！
请问作者有没有考虑过在文章右边设置一个滑动目录？
目前看来，对较长文章来说，没有目录可能看起来有些不方便

**Comment by wan92hen** [comment]
可以考虑下增加个文章内容目录。

> 感谢！已经调整好啦！ 请问作者有没有考虑过在文章右边设置一个滑动目录？ 目前看来，对较长文章来说，没有目录可能看起来有些不方便

**Comment by wan92hen** [comment]
https://github.com/wan92hen/theme-terminal/releases/tag/1.1.0 最新版本中支持了显示文章目录。
