### ISSUE TITLE
可不可以增加搜索框?

### ISSUE THREAD

**Issue by binbinLeader** [wan92hen/theme-terminal#3]
希望可以加入搜索框, 不然的话, 使用起来不方便, 不如不用, 貌似加搜索框也挺方便的, 希望可以采纳

**Comment by wan92hen** [comment]
感谢反馈，之后会增加对[搜索插件](https://github.com/halo-sigs/plugin-search-widget)的支持。

**Comment by wan92hen** [comment]
[Release v0.0.5](https://github.com/wan92hen/theme-terminal/releases/tag/v0.0.5) 中已支持。
