### ISSUE TITLE
加入登陆和评论

### ISSUE THREAD

**Issue by Erzbir** [wan92hen/theme-terminal#8]
能否加入登陆入口和评论功能呢

**Comment by wan92hen** [comment]
你好，抱歉这么晚才回复。
评论功能现在是有的，需要安装下[评论插件](https://halo.run/store/apps/app-YXyaD)。
![image](https://github.com/wan92hen/theme-terminal/assets/27671436/0bc10101-633a-4dd6-895e-06f47a1addd6)

**Comment by wan92hen** [comment]
由于没有收到反馈，我这边先关闭这个 issue 了。
