### ISSUE TITLE
加入/links页面

### ISSUE THREAD

**Issue by buerka** [wan92hen/theme-terminal#9]
能否加入/links页面?感谢

**Comment by wan92hen** [comment]
OK，下个 release 加下这个。

**Comment by wan92hen** [comment]
在最新的 [v0.0.8 Release](https://github.com/wan92hen/theme-terminal/releases/tag/v0.0.8) 中已支持，欢迎体验并反馈~

**Comment by buerka** [comment]
辛苦了，非常感谢！
